### ISSUE TITLE
Need Fixes, David pls halp

### ISSUE THREAD

**Issue by Kixiron** [FlatPackBots/Hjalpare#6]
DM, User-Info, Hackban, and Penis,

**Comment by Kixiron** [comment]
I suck at this @iDavidW

**Comment by iDavidW** [comment]
I took a look at things while I was resolving conflicts to close my pull request, and I think I have fixes for them, which I'll get started on shortly :3

**Comment by iDavidW** [comment]
Hackban re implemented and functioning.
Penis fixed.
User-Info now responds to author, but more fixes with the embed are necessary.
Haven't looked into DM too much yet.

**Comment by iDavidW** [comment]
user info fixed and functioning, and DM has been replaced by contact, so I'll go ahead and close this particular issue.
